server:
  port: 8082

spring:
  application:
    name: postulacion-service

  datasource:
    url: jdbc:mysql://localhost:3306/bd_postulacion_dev
    username: root
    password: Root2026!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      vacante-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  retry:
    instances:
      vacante-service:
        max-attempts: 3
        wait-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

mensaje:
  bienvenida: "Módulo de Postulaciones activo"